### ISSUE TITLE
Tracking upstream Rust feature stability and RFCs that affect wasm

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#63]
### Awaiting Stability / Implementation

* [x] [Allocator traits and std::heap](https://github.com/rust-lang/rust/issues/32838)

* [x] [Tracking issue for changing the global, default allocator (RFC 1974)](https://github.com/rust-lang/rust/issues/27389)

* [x] [`feature(proc_macro)`](https://github.com/rust-lang/rust/issues/38356) (used heavily by `wasm-bindgen`)

* [ ] [Custom test frameworks](https://github.com/rust-lang/rust/issues/50297)

### RFCs

* [X] [eRFC: Custom test frameworks](https://github.com/rust-lang/rfcs/pull/2318) The eRFC was merged, and this is now awaiting implementation and then stabilization.

* [ ] [RFC: Introduce panic_thin, a fmtless alternative to panic_fmt](https://github.com/rust-lang/rfcs/pull/2305)

### Unstable and Need RFC

* [x] [Intrinsics for growing and insecting wasm memory](https://github.com/rust-lang-nursery/rust-wasm/issues/23)

### Completely Unimplemented and Need RFC

* [ ] Cargo templates

### Bugs

* [ ] [LTO ignored for all crate types if any crate type doesn't support it](https://github.com/rust-lang/rust/issues/51009) This means that LTO is disabled if you enable rlibs and cdylibs for both native testing/benching and building for wasm.

----------------

Please add links to other RFCs and feature stabilization issues that are relevant and help us keep them up to date!

**Comment by mgattozzi** [comment]
Do we want to open an issue for upstream non rust ones like llvm or the webassembly group itself?

**Comment by fitzgen** [comment]
> Do we want to open an issue for upstream non rust ones like llvm or the webassembly group itself?

For sure!

**Comment by fitzgen** [comment]
* [ ] [__extendsfdf2 function erroneously emitted in wasm32-unknown-unknown](https://github.com/rust-lang/rust/issues/48391)

**Comment by fitzgen** [comment]
Does anyone know the latest cargo template (pre) RFC? Would like to add it here.

**Comment by mgattozzi** [comment]
Maybe someone on the @rust-lang/cargo team would know. The only template pre-rfc is the old one on internals.

**Comment by matklad** [comment]
@mgattozzi there's no any active RFC about templates currently, the discussion died out :(

**Comment by mgattozzi** [comment]
@matklad that's unfortunate. cargo does everything I need, but this is the one feature I still want.

**Comment by fitzgen** [comment]
I added a new "completely unimplemented and need rfc" section for the templates ;)

**Comment by alexcrichton** [comment]
I think that this has sat around long enough that we've solved enough and otherwise this isn't tracking too too much any more so I'm going to close it.
